
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erick cerati
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("NC.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        textField9 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        siguiente = new java.awt.Button();
        jButton1 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel13.setText("jLabel13");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Approximate Entropy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 56, 121, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fast Fourier Transform");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 86, 129, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Analysis Hjorth Fractal Dimension");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(37, 116, 190, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Hurst Exponent");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 140, 87, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Petrosian Fractal Dimension");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(37, 164, 158, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Spectral Entropy");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(37, 188, 94, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("SVD Entropy");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(37, 278, 69, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Correlation Dimension");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(37, 218, 125, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Lyapunov Exponet");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(37, 248, 104, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Posibles  Diagnósticos:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(298, 56, 127, 14);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(298, 86, 201, 96);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Especialistas:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(298, 188, 75, 14);

        textField1.setBackground(new java.awt.Color(255, 0, 0));
        textField1.setEditable(false);
        textField1.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField1);
        textField1.setBounds(237, 56, 30, 20);

        textField2.setBackground(new java.awt.Color(0, 204, 0));
        textField2.setEditable(false);
        textField2.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField2);
        textField2.setBounds(237, 86, 30, 20);

        textField3.setBackground(new java.awt.Color(255, 255, 0));
        textField3.setEditable(false);
        textField3.setMinimumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField3);
        textField3.setBounds(237, 110, 30, 20);

        textField4.setBackground(new java.awt.Color(255, 0, 0));
        textField4.setEditable(false);
        textField4.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField4);
        textField4.setBounds(237, 134, 30, 20);

        textField5.setBackground(new java.awt.Color(0, 204, 0));
        textField5.setEditable(false);
        textField5.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField5);
        textField5.setBounds(237, 158, 30, 20);

        textField6.setBackground(new java.awt.Color(255, 255, 0));
        textField6.setEditable(false);
        textField6.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField6);
        textField6.setBounds(237, 188, 30, 20);

        textField7.setBackground(new java.awt.Color(255, 255, 0));
        textField7.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField7);
        textField7.setBounds(237, 218, 30, 20);

        textField8.setBackground(new java.awt.Color(0, 204, 0));
        textField8.setEditable(false);
        textField8.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField8);
        textField8.setBounds(237, 248, 30, 20);

        textField9.setBackground(new java.awt.Color(255, 0, 0));
        textField9.setEditable(false);
        textField9.setPreferredSize(new java.awt.Dimension(30, 20));
        getContentPane().add(textField9);
        textField9.setBounds(237, 278, 30, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        label1.setBackground(new java.awt.Color(204, 204, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Resultados");
        jPanel1.add(label1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 650, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario2.png"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(520, 150, 120, 130);

        jLabel16.setBackground(new java.awt.Color(255, 255, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NCX.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(520, 20, 120, 80);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText(" NeuroComplex");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(530, 100, 90, 14);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("MARIA DEL CARMEN IRIGOYEN MALDONADO \nSUR 136 (HOSPITAL ABC) No.116, CONS. 401 \nCol. LAS AMERICAS \nDel. ALVARO OBREGON \nTel. 52722526, 52723698, 26142370 \nNota: NEUROLOGIA ADULTOS Y PEDIATRICA. ");
        jTextArea2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(300, 170, 201, 96);

        jLabel17.setBackground(new java.awt.Color(0, 204, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel17.setText("Salud que se comparte");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(530, 120, 120, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 640, 280);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        siguiente.setLabel("Continuar");
        jPanel3.add(siguiente);
        siguiente.setBounds(430, 330, 70, 30);

        jButton1.setText("Continuar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton1);
        jButton1.setBounds(533, 10, 100, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(-10, 320, 690, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Label label1;
    private java.awt.Button siguiente;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
